# Generated by Django 5.0.6 on 2025-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='eligibility_data',
            field=models.JSONField(default=dict),
        ),
    ]
