# Generated by Django 5.0.6 on 2025-01-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donor_eligibility_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='database',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
